<script lang="ts" generics="Schema extends z.ZodRawShape">
  import { setContext, type Snippet } from "svelte";
  import { getElementByName, applyFormDefaultValues } from "@utils/dom";
  import { z } from "zod";
  import { removeBlanks } from "@utils/objects";

  type Props = {
    children: Snippet;
    onsubmit: (formParams: z.infer<z.ZodObject<Schema>>) => unknown;
    defaultValues?: Partial<z.infer<z.ZodObject<Schema>>>;
    class?: string;
    id?: string;
    schema: z.ZodObject<Schema>;
  };

  // Apply default values to inputs on default values change
  $effect(() => {
    if (!defaultValues) return;
    applyFormDefaultValues(schema.partial().parse(removeBlanks(defaultValues)));
  });

  const isSubmitting = $state({ isSubmitting: false });

  const onsubmitWrapper = async (e: SubmitEvent) => {
    e.preventDefault();

    if (isSubmitting.isSubmitting) return;
    isSubmitting.isSubmitting = true;

    const baseFormData = new FormData(e.target as HTMLFormElement);

    // Delete blank values from formData and unwanted values
    // (names generated by generateId(), for combobox)
    // and convert to object
    const formData = Object.fromEntries(
      [...baseFormData].filter(
        ([key, value]) =>
          !key.startsWith("RAND_ID") && (value as string).trim() !== ""
      )
    );

    try {
      const validatedFormData = schema.parse(formData);

      // Add extra keys that were not part of zod schema
      Object.entries(formData).forEach(([key, value]) => {
        if (!(key in validatedFormData)) {
          // @ts-expect-error this is fine
          validatedFormData[key] = value;
        }
      });

      await onsubmit(validatedFormData);
      (e.target as HTMLFormElement).reset();
    } catch (error) {
      if (!(error instanceof z.ZodError)) throw error;

      error.issues.forEach((issue) => {
        issue.path.forEach((fieldName) => {
          const field = getElementByName(fieldName.toString());
          field.dataset.invalid = "true";
        });
      });
    } finally {
      isSubmitting.isSubmitting = false;
    }
  };

  let {
    children,
    onsubmit,
    defaultValues,
    schema,
    class: className,
    id
  }: Props = $props();

  setContext("defaultValues", defaultValues);
  setContext("isSubmitting", isSubmitting);
</script>

<form {id} onsubmit={onsubmitWrapper} class={className}>
  {@render children()}
</form>
